name: CD

on:
  push:
    branches:
    - master

jobs:

  CD:
    runs-on: ubuntu-latest

    steps: 
    - uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/labauth.maximilian.mairinger.com
          git pull
          /root/.nvm/versions/node/v14.0.0/bin/node -v > abc
          /root/.nvm/versions/node/v14.0.0/bin/pm2 reload ecosystem.config.js
